url: 
title: Code for Formers


google_analytics_tracking_id: 
google_analytics_tracking_domain: auto

exclude: ["Gemfile", "Gemfile.lock", "bin"]

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown

disqus_shortname: 

twitter_username: 

encoding: UTF-8
